/**
 * Regenerate the SOBBU platform legal-document artifacts from the markdown
 * sources of truth in `legal/*.md`:
 *
 *  1. Re-embeds the markdown into
 *     `lib/legal-docs/src/templates.generated.ts` (used by the api-server
 *     signing routes and the admin-portal signing form — the bundled server
 *     has no `legal/` directory at runtime, so templates must be embedded).
 *  2. Renders the blank template PDFs and writes byte-identical copies to
 *     BOTH `legal/` and `artifacts/admin-portal/public/legal/` (the portal's
 *     Legal & Agreements page serves the latter).
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run generate-legal-pdfs            # regenerate
 *   pnpm --filter @workspace/scripts run generate-legal-pdfs -- --check # assert in sync
 *
 * Exit codes: 0 = written / in sync; 1 = drift (--check) or error.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  AGREEMENT_SLOTS,
  AGREEMENT_TITLES,
  AGREEMENT_FILE_BASES,
  type AgreementSlot,
} from "@workspace/legal-docs";
import { renderLegalPdf, pdfToBuffer } from "@workspace/legal-docs/pdf";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..");
const LEGAL_DIR = path.resolve(repoRoot, "legal");
const PORTAL_LEGAL_DIR = path.resolve(repoRoot, "artifacts", "admin-portal", "public", "legal");
const GENERATED_PATH = path.resolve(repoRoot, "lib", "legal-docs", "src", "templates.generated.ts");

export function readMarkdownSources(): Record<AgreementSlot, string> {
  const out = {} as Record<AgreementSlot, string>;
  for (const slot of AGREEMENT_SLOTS) {
    out[slot] = readFileSync(path.join(LEGAL_DIR, `${AGREEMENT_FILE_BASES[slot]}.md`), "utf8");
  }
  return out;
}

export function buildGeneratedSource(sources: Record<AgreementSlot, string>): string {
  return [
    "// AUTO-GENERATED by `pnpm --filter @workspace/scripts run generate-legal-pdfs`.",
    "// DO NOT EDIT — source of truth is legal/<file>.md at the repo root.",
    "// A staleness test in scripts/src compares this file against the sources.",
    "",
    "export const LEGAL_TEMPLATES = {",
    `  msa: ${JSON.stringify(sources.msa)},`,
    `  user_agreement: ${JSON.stringify(sources.user_agreement)},`,
    '} as const satisfies Record<"msa" | "user_agreement", string>;',
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes("--check");
  const sources = readMarkdownSources();
  const expected = buildGeneratedSource(sources);

  if (checkOnly) {
    const current = existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, "utf8") : "";
    if (current !== expected) {
      console.error(
        "legal templates are stale: lib/legal-docs/src/templates.generated.ts does not match legal/*.md.\n" +
          "Run: pnpm --filter @workspace/scripts run generate-legal-pdfs",
      );
      process.exit(1);
    }
    console.log("legal templates are in sync.");
    return;
  }

  writeFileSync(GENERATED_PATH, expected);
  console.log(`wrote ${path.relative(repoRoot, GENERATED_PATH)}`);

  for (const slot of AGREEMENT_SLOTS) {
    const doc = renderLegalPdf({ title: AGREEMENT_TITLES[slot], markdown: sources[slot] });
    const buf = await pdfToBuffer(doc);
    const fileName = `${AGREEMENT_FILE_BASES[slot]}.pdf`;
    for (const dir of [LEGAL_DIR, PORTAL_LEGAL_DIR]) {
      const target = path.join(dir, fileName);
      writeFileSync(target, buf);
      console.log(`wrote ${path.relative(repoRoot, target)} (${buf.length} bytes)`);
    }
  }
}

const isMainModule =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMainModule) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
